/**
 * Procedural surface generators.
 *
 * Each generator produces three tiling maps at a given resolution:
 *   albedo    — the base colour of the surface
 *   roughness — per-texel micro-surface variation (this is what sells "wood"
 *               versus "plastic" far more than colour does)
 *   height    — a greyscale field converted into a normal map by the caller
 *
 * Everything is drawn from noise and maths, so the repository carries no image
 * assets, has no texture licensing to track, and stays a few hundred kilobytes.
 * When photographic PBR scans are added later they can be dropped in behind the
 * same `SurfaceMaps` interface without touching any calling code.
 *
 * All generators are written to TILE SEAMLESSLY across a `tileMetres` square of
 * world space, so a floor of any size repeats without a visible grid.
 */

import { ValueNoise2D, fbm, mulberry32 } from './noise';
import { clamp255, hexToRgb, mixRgb, renderHeightField } from './textureUtils';

export interface SurfaceMaps {
  albedo: ImageData;
  roughness: ImageData;
  height: ImageData;
  /** How strongly the height field is expressed as a normal map. */
  normalStrength: number;
  /** World size in metres that one texture repeat covers. */
  tileMetres: number;
}

/** Shared noise lattice period. Powers of two keep the tiling maths exact. */
const NOISE_PERIOD = 64;

/** Writes one RGB texel into an ImageData buffer. */
function setPixel(image: ImageData, index: number, r: number, g: number, b: number): void {
  image.data[index] = clamp255(r);
  image.data[index + 1] = clamp255(g);
  image.data[index + 2] = clamp255(b);
  image.data[index + 3] = 255;
}

/** Writes one greyscale value (used for the roughness map). */
function setGrey(image: ImageData, index: number, value: number): void {
  setPixel(image, index, value, value, value);
}

/* ────────────────────────────── Wood ────────────────────────────── */

export interface WoodOptions {
  /** Darkest tone in the grain. */
  darkColor: string;
  /** Lightest tone in the grain. */
  lightColor: string;
  /** Plank dimensions in metres. */
  plankWidth: number;
  plankLength: number;
  /** 0–1: how visible the grain figuring is. */
  grainContrast: number;
  /** Base roughness; satin-lacquered oak sits around 0.5, raw timber near 0.8. */
  baseRoughness: number;
  seed: number;
  tileMetres: number;
}

/**
 * Plank flooring with staggered joints and directional grain.
 *
 * Planks run along the X axis (the U texture direction). Grain is generated by
 * sampling noise that is stretched heavily along the plank so that the figuring
 * forms long streaks rather than isotropic blobs, then folded through a sine to
 * create the growth-ring banding characteristic of sawn timber.
 */
export function generateWood(size: number, options: WoodOptions): SurfaceMaps {
  const albedo = new ImageData(size, size);
  const roughness = new ImageData(size, size);
  const noise = new ValueNoise2D(NOISE_PERIOD, options.seed);
  const random = mulberry32(options.seed ^ 0x9e37);

  const dark = hexToRgb(options.darkColor);
  const light = hexToRgb(options.lightColor);

  // Round to whole planks per tile so the pattern repeats without a seam.
  const rows = Math.max(1, Math.round(options.tileMetres / options.plankWidth));
  const cols = Math.max(1, Math.round(options.tileMetres / options.plankLength));

  // Each plank gets its own slight tone shift, as real timber does.
  const plankTone: number[] = [];
  for (let i = 0; i < rows * cols; i++) plankTone.push(random() * 2 - 1);

  for (let y = 0; y < size; y++) {
    const v = y / size;
    const rowPos = v * rows;
    const row = Math.floor(rowPos);
    const localV = rowPos - row;

    for (let x = 0; x < size; x++) {
      const u = x / size;

      // Offsetting each row by a constant fraction staggers the end joints.
      const colPos = u * cols + row * 0.37 * cols;
      const col = Math.floor(colPos);
      const localU = colPos - col;

      // Long streaks: low frequency along the plank, high frequency across it.
      const streak = fbm(noise, u * 5 + col * 3.7, v * 70 + row * 11.3, 4, NOISE_PERIOD);
      // Fold through a sine to produce growth-ring banding.
      const rings = Math.abs(Math.sin((localV * 9 + streak * 5.5) * Math.PI));
      let grain = 0.55 * streak + 0.45 * rings;

      // Per-plank tone variation.
      const toneIndex = (((row * cols + col) % plankTone.length) + plankTone.length) % plankTone.length;
      grain += (plankTone[toneIndex] ?? 0) * 0.12;

      // Blend between the two wood tones, biased by the contrast setting.
      const t = Math.min(1, Math.max(0, 0.5 + (grain - 0.5) * (0.6 + options.grainContrast)));
      let color = mixRgb(dark, light, t);

      // Darken the bevelled joints between planks.
      const edgeV = Math.min(localV, 1 - localV);
      const edgeU = Math.min(localU, 1 - localU);
      const seamWidth = 0.035;
      const seam = Math.min(1, Math.min(edgeV, edgeU * 0.6) / seamWidth);
      const seamShade = 0.45 + 0.55 * seam;
      color = { r: color.r * seamShade, g: color.g * seamShade, b: color.b * seamShade };

      const index = (y * size + x) * 4;
      setPixel(albedo, index, color.r, color.g, color.b);

      // Denser late-growth grain is slightly glossier; joints are matte.
      const rough = options.baseRoughness + (1 - grain) * 0.16 - (1 - seam) * -0.12;
      setGrey(roughness, index, rough * 255);
    }
  }

  // Height: joints recessed, grain very lightly raised.
  const height = renderHeightField(size, (u, v) => {
    const rowPos = v * rows;
    const row = Math.floor(rowPos);
    const localV = rowPos - row;
    const colPos = u * cols + row * 0.37 * cols;
    const localU = colPos - Math.floor(colPos);

    const edgeV = Math.min(localV, 1 - localV);
    const edgeU = Math.min(localU, 1 - localU);
    const seam = Math.min(1, Math.min(edgeV, edgeU * 0.6) / 0.035);

    const streak = fbm(noise, u * 5, v * 70, 3, NOISE_PERIOD);
    return 0.15 + seam * 0.75 + streak * 0.1;
  });

  return { albedo, roughness, height, normalStrength: 2.2, tileMetres: options.tileMetres };
}

/* ────────────────────────────── Tile ────────────────────────────── */

export interface TileOptions {
  /** Edge length of one tile, in metres. */
  tileSize: number;
  /** Grout gap width, in metres. */
  groutWidth: number;
  primaryColor: string;
  /** Second colour; equal to primary for a plain tile, different for a checker. */
  secondaryColor: string;
  groutColor: string;
  /** 0–1 mottling within each tile face. */
  variation: number;
  baseRoughness: number;
  seed: number;
  tileMetres: number;
}

/**
 * Ceramic or stone tile with grout lines.
 *
 * Grout is modelled as a recessed, much rougher band around each tile, which is
 * what makes tiled floors read correctly under a moving light — the specular
 * highlight breaks at every joint.
 */
export function generateTile(size: number, options: TileOptions): SurfaceMaps {
  const albedo = new ImageData(size, size);
  const roughness = new ImageData(size, size);
  const noise = new ValueNoise2D(NOISE_PERIOD, options.seed);
  const random = mulberry32(options.seed ^ 0x51ed);

  const primary = hexToRgb(options.primaryColor);
  const secondary = hexToRgb(options.secondaryColor);
  const grout = hexToRgb(options.groutColor);

  const tiles = Math.max(1, Math.round(options.tileMetres / options.tileSize));
  // Grout width expressed as a fraction of one tile cell.
  const groutFraction = Math.min(0.25, options.groutWidth / options.tileSize);

  const tileTone: number[] = [];
  for (let i = 0; i < tiles * tiles; i++) tileTone.push(random());

  for (let y = 0; y < size; y++) {
    const v = y / size;
    const cellY = v * tiles;
    const ty = Math.floor(cellY);
    const localV = cellY - ty;

    for (let x = 0; x < size; x++) {
      const u = x / size;
      const cellX = u * tiles;
      const tx = Math.floor(cellX);
      const localU = cellX - tx;

      const index = (y * size + x) * 4;

      // Distance to the nearest cell edge, in cell units.
      const edge = Math.min(localU, 1 - localU, localV, 1 - localV);
      const inGrout = edge < groutFraction * 0.5;

      if (inGrout) {
        // Grout carries its own fine grit.
        const grit = fbm(noise, u * 90, v * 90, 3, NOISE_PERIOD) * 0.18 + 0.91;
        setPixel(albedo, index, grout.r * grit, grout.g * grit, grout.b * grit);
        setGrey(roughness, index, 0.94 * 255);
        continue;
      }

      // Checkerboard selection; identical colours simply yield a plain tile.
      const isAlternate = (tx + ty) % 2 === 1;
      const base = isAlternate ? secondary : primary;

      // Mottling within the face, plus a per-tile tone shift.
      const mottle = fbm(noise, u * 14 + tx * 5.1, v * 14 + ty * 7.9, 4, NOISE_PERIOD);
      const toneIndex = (((ty * tiles + tx) % tileTone.length) + tileTone.length) % tileTone.length;
      const perTile = ((tileTone[toneIndex] ?? 0.5) - 0.5) * 0.08 * options.variation;
      const shade = 1 + (mottle - 0.5) * 0.35 * options.variation + perTile;

      setPixel(albedo, index, base.r * shade, base.g * shade, base.b * shade);

      // Slight roughness variation keeps the glaze from looking like plastic.
      setGrey(roughness, index, (options.baseRoughness + (mottle - 0.5) * 0.1) * 255);
    }
  }

  const height = renderHeightField(size, (u, v) => {
    const cellX = u * tiles;
    const cellY = v * tiles;
    const localU = cellX - Math.floor(cellX);
    const localV = cellY - Math.floor(cellY);
    const edge = Math.min(localU, 1 - localU, localV, 1 - localV);
    const half = groutFraction * 0.5;

    // Ramp up out of the grout channel over a short distance for a soft bevel.
    if (edge < half) return 0.05;
    return Math.min(1, 0.05 + ((edge - half) / (half * 1.6)) * 0.95);
  });

  return { albedo, roughness, height, normalStrength: 3.0, tileMetres: options.tileMetres };
}

/* ──────────────────────────── Concrete ──────────────────────────── */

export interface ConcreteOptions {
  baseColor: string;
  /** Colour of the darker mineral mottling. */
  mottleColor: string;
  /** 0–1 how polished the surface is; lowers roughness and flattens the height. */
  polish: number;
  seed: number;
  tileMetres: number;
}

/** Poured or polished concrete: broad cloudy mottling plus fine aggregate speckle. */
export function generateConcrete(size: number, options: ConcreteOptions): SurfaceMaps {
  const albedo = new ImageData(size, size);
  const roughness = new ImageData(size, size);
  const broad = new ValueNoise2D(NOISE_PERIOD, options.seed);
  const fine = new ValueNoise2D(NOISE_PERIOD, options.seed ^ 0x2f19);

  const base = hexToRgb(options.baseColor);
  const mottle = hexToRgb(options.mottleColor);
  const baseRoughness = 0.92 - options.polish * 0.55;

  for (let y = 0; y < size; y++) {
    const v = y / size;
    for (let x = 0; x < size; x++) {
      const u = x / size;
      const index = (y * size + x) * 4;

      const clouds = fbm(broad, u * 6, v * 6, 5, NOISE_PERIOD);
      const speckle = fbm(fine, u * 110, v * 110, 2, NOISE_PERIOD);

      // Clouds drive the colour; speckle adds the visible aggregate grit.
      const t = Math.min(1, Math.max(0, clouds * 0.85 + (speckle - 0.5) * 0.3));
      const color = mixRgb(base, mottle, t);

      setPixel(albedo, index, color.r, color.g, color.b);
      setGrey(roughness, index, (baseRoughness + (speckle - 0.5) * 0.12) * 255);
    }
  }

  const height = renderHeightField(size, (u, v) => {
    const clouds = fbm(broad, u * 6, v * 6, 4, NOISE_PERIOD);
    const speckle = fbm(fine, u * 110, v * 110, 2, NOISE_PERIOD);
    return 0.5 + (clouds - 0.5) * 0.4 + (speckle - 0.5) * 0.6;
  });

  // Polishing physically flattens the surface, so the normal map eases off too.
  return {
    albedo,
    roughness,
    height,
    normalStrength: 1.6 - options.polish * 1.1,
    tileMetres: options.tileMetres,
  };
}

/* ───────────────────────────── Carpet ───────────────────────────── */

export interface CarpetOptions {
  baseColor: string;
  /** Fibre-to-fibre tonal spread; wool loops vary more than synthetic. */
  fibreVariation: number;
  seed: number;
  tileMetres: number;
}

/**
 * Woven carpet or rug pile.
 *
 * The look comes almost entirely from the normal map: a dense, high-frequency
 * height field reads as fibre under raking light. Albedo stays near-uniform,
 * and roughness is pinned high because textiles have essentially no specular
 * lobe — any gloss here instantly reads as plastic.
 */
export function generateCarpet(size: number, options: CarpetOptions): SurfaceMaps {
  const albedo = new ImageData(size, size);
  const roughness = new ImageData(size, size);
  const fibre = new ValueNoise2D(NOISE_PERIOD, options.seed);
  const weave = new ValueNoise2D(NOISE_PERIOD, options.seed ^ 0x77c1);

  const base = hexToRgb(options.baseColor);

  for (let y = 0; y < size; y++) {
    const v = y / size;
    for (let x = 0; x < size; x++) {
      const u = x / size;
      const index = (y * size + x) * 4;

      const strands = fbm(fibre, u * 150, v * 150, 2, NOISE_PERIOD);
      const clumps = fbm(weave, u * 18, v * 18, 3, NOISE_PERIOD);

      const shade =
        1 + (strands - 0.5) * 0.28 * options.fibreVariation + (clumps - 0.5) * 0.14;

      setPixel(albedo, index, base.r * shade, base.g * shade, base.b * shade);
      setGrey(roughness, index, 0.97 * 255);
    }
  }

  const height = renderHeightField(size, (u, v) => {
    const strands = fbm(fibre, u * 150, v * 150, 2, NOISE_PERIOD);
    const clumps = fbm(weave, u * 18, v * 18, 3, NOISE_PERIOD);
    return strands * 0.75 + clumps * 0.25;
  });

  return { albedo, roughness, height, normalStrength: 3.4, tileMetres: options.tileMetres };
}

/* ───────────────────────────── Marble ───────────────────────────── */

export interface MarbleOptions {
  baseColor: string;
  veinColor: string;
  /** How contorted the veining is. */
  turbulence: number;
  seed: number;
  tileMetres: number;
}

/**
 * Veined marble.
 *
 * Classic approach: take a linear gradient, warp its coordinate with turbulent
 * noise, then run it through a sine. The warping is what turns regular stripes
 * into the wandering, branching veins that read as stone.
 */
export function generateMarble(size: number, options: MarbleOptions): SurfaceMaps {
  const albedo = new ImageData(size, size);
  const roughness = new ImageData(size, size);
  const noise = new ValueNoise2D(NOISE_PERIOD, options.seed);
  const detail = new ValueNoise2D(NOISE_PERIOD, options.seed ^ 0x1b3d);

  const base = hexToRgb(options.baseColor);
  const vein = hexToRgb(options.veinColor);

  /** Vein intensity at a point, 0 = clean stone, 1 = vein core. */
  const veinAt = (u: number, v: number): number => {
    const warp = fbm(noise, u * 4, v * 4, 5, NOISE_PERIOD) * options.turbulence;
    // Integer multipliers on u and v keep the sine phase continuous across the
    // tile boundary, so the veins do not visibly break at the repeat.
    const stripes = Math.sin((u * 2 + v * 4 + warp) * Math.PI * 2);
    const core = Math.pow(1 - Math.abs(stripes), 6);
    const fracture = Math.pow(fbm(detail, u * 22, v * 22, 3, NOISE_PERIOD), 2) * 0.35;
    return Math.min(1, core + fracture);
  };

  for (let y = 0; y < size; y++) {
    const v = y / size;
    for (let x = 0; x < size; x++) {
      const u = x / size;
      const index = (y * size + x) * 4;

      const intensity = veinAt(u, v);
      const color = mixRgb(base, vein, intensity);

      setPixel(albedo, index, color.r, color.g, color.b);
      // Veins are a softer mineral than the matrix and polish slightly duller.
      setGrey(roughness, index, (0.18 + intensity * 0.22) * 255);
    }
  }

  const height = renderHeightField(size, (u, v) => 0.7 - veinAt(u, v) * 0.35);

  return { albedo, roughness, height, normalStrength: 0.7, tileMetres: options.tileMetres };
}
